name = "expense-management-system"
compatibility_date = "2024-09-25"
pages_build_output_dir = "."

[env.production]
compatibility_date = "2024-09-25"

[env.production.vars]
ENVIRONMENT = "production"

# 注意：敏感信息应该在Cloudflare Dashboard中设置，而不是在这里
# DATABASE_URL = "设置在Cloudflare Dashboard环境变量中"
# SECRET_KEY = "设置在Cloudflare Dashboard环境变量中"
# CLOUDINARY_URL = "设置在Cloudflare Dashboard环境变量中"

[build]
command = "pip install -r requirements.txt"
cwd = "../.."

[env.preview]
compatibility_date = "2024-09-25"

[env.preview.vars]
ENVIRONMENT = "preview"
